name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Create ECR Repository (if not exists)
        run: |
          aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY }}-patient || \
          aws ecr create-repository --repository-name ${{ secrets.ECR_REPOSITORY }}-patient

      - name: Create ECR Repository (if not exists)
        run: |
          aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY }}-appointment || \
          aws ecr create-repository --repository-name ${{ secrets.ECR_REPOSITORY }}-appointment
     
      - name: Build Docker Image (Patient)
        working-directory: app
        run: |
          echo "Building patient image..."
          docker build -t ${{ secrets.ECR_REPOSITORY }}-patient -f Dockerfile.patient .

      - name: Tag and Push Docker Image (Patient)
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}-patient:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}-patient:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}-patient:latest

      - name: Build Docker Image (Appointment)
        working-directory: app
        run: |
          echo "Building appointment image..."
          docker build -t ${{ secrets.ECR_REPOSITORY }}-appointment -f Dockerfile.appointment .

      - name: Tag and Push Docker Image (Appointment)
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}-appointment:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}-appointment:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}-appointment:latest
